# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/" # Location of package manifests
    schedule:
      interval: "monthly"
  - package-ecosystem: "julia"
    # Location of Julia projects
    directories:
      - "/"
      - "/docs"
      - "/paper"
      - "/lib/EphemerisSourcesBase"
      - "/lib/EphemerisSourcesBase/docs"
      - "/lib/HorizonsEphemeris"
      - "/lib/HorizonsEphemeris/docs"
      - "/lib/HorizonsAPI"
      - "/lib/HorizonsAPI/docs"
      - "/lib/SPICEKernels/gen"
      - "/lib/SPICEKernels"
      - "/lib/SPICEKernels/docs"
      - "/lib/SPICEBodies"
      - "/lib/SPICEBodies/docs"
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: "EphemerisSources"
      - dependency-name: "EphemerisSourcesBase"
      - dependency-name: "HorizonsEphemeris"
      - dependency-name: "HorizonsAPI"
      - dependency-name: "SPICEKernels"
      - dependency-name: "SPICEBodies"
    groups:
      per-dependency:
        group-by: dependency-name
