# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/" # Location of package manifests
    schedule:
      interval: "monthly"
    groups:
      actions:
        patterns:
          - "*"

  - package-ecosystem: "julia"
    directories:
      - "/"
      - "/docs"
      - "/paper"
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: "EphemerisSources"
      - dependency-name: "EphemerisSourcesBase"
      - dependency-name: "HorizonsEphemeris"
      - dependency-name: "HorizonsAPI"
      - dependency-name: "SPICEKernels"
      - dependency-name: "SPICEBodies"
    groups:
      julia:
        patterns:
          - "*"
