project:
  type: manuscript
  output-dir: _manuscript
  post-render: ./post.sh

manuscript:
  article: index.qmd

format:
  html:
    comments:
      hypothesis: true
  arxiv-pdf:
    output-file: paper
  markdown:
    output-file: paper

execute:
  echo: true
