project:
  type: manuscript
  output-dir: _manuscript
  post-render: ./post.sh

manuscript:
  article: index.qmd

format:
  html:
    comments:
      hypothesis: true
  markdown:
    output-file: paper

execute:
  echo: true
  freeze: true