project:
  type: manuscript
  output-dir: _manuscript
  post-render: ./post.sh

manuscript:
  article: paper.md

format:
  html:
    include-before-body: 
      text: |
        <div class="callout-warning callout callout-style-simple">
            <div class="callout-body d-flex">
                <div class="callout-icon-container">
                    <i class="callout-icon"></i>
                    </div>
                    <div class="callout-body-container">
                    <p><i>
                      This page is a **pre-print**! The published paper is available at 
                      the Journal of Open Source Software.
                    </i></p>
                </div>
            </div>
        </div>

        :::

    comments:
      hypothesis: true
    theme: 
      light: flatly
      dark: darkly

execute: 
  cache: false
  freeze: false
  echo: true