project:
  type: manuscript
  output-dir: _manuscript
  post-render: ./post.sh

manuscript:
  article: paper.md

format:
  html:
    css: styles.css
    include-before-body: 
      text: |
        <div class="callout-note callout callout-style-simple">
            <div class="callout-body d-flex">
                <div class="callout-icon-container">
                    <i class="callout-icon"></i>
                    </div>
                    <div class="callout-body-container">
                    <p><i>
                      This page is a <b>pre-print</b>! The published paper is available at 
                      the <a jref="https://joss.theoj.org">Journal of Open Source Software</a>.
                    </i></p>
                </div>
            </div>
        </div>

    comments:
      hypothesis: true
    theme: 
      light: flatly
      dark: darkly

execute: 
  cache: false
  freeze: false
  echo: true