project:
  type: manuscript
  post-render: post.sh

manuscript:
  article: paper.md
  resources: 
    - "*.bib"

format:
  html:
    title-block-style: manuscript
    title-block-banner-color: white
    title-block-banner: "#474b63"
    include-in-header: 
      text: <meta theme-color content="#474b63"/>
    include-before-body: 
      text: |
        <div class="callout-note callout callout-style-simple">
            <div class="callout-body d-flex">
                <div class="callout-icon-container">
                    <i class="callout-icon"></i>
                    </div>
                    <div class="callout-body-container">
                    <p><i>
                      This page is a <b>pre-print</b>! The published paper is available at 
                      the <a href="https://joss.theoj.org">Journal of Open Source Software</a>.
                    </i></p>
                </div>
            </div>
        </div>

    theme: 
      light: 
        - _style/light.scss
        - _style/common.scss
        - _style/latte.scss
      dark: 
        - _style/dark.scss
        - _style/common.scss
        - _style/mocha.scss

    css: _style/static.css

    mainfont: "'Noto Sans', sans-serif"
    monofont: "'Noto Sans Mono', monospace;"
execute: 
  cache: false
  freeze: false
  echo: true