project:
  type: manuscript
  output-dir: _manuscript
  post-render: ./post.sh

manuscript:
  article: index.qmd

format:
  html:
    comments:
      hypothesis: true
    theme: 
      light: flatly
      dark: darkly
  markdown:
    output-file: paper

execute: 
  cache: false
  freeze: false
  echo: true